Prevent build in 32bit if found system libiodbc

diff --git a/gis/saga-gis/saga-gis.SlackBuild b/gis/saga-gis/saga-gis.SlackBuild
--- a/gis/saga-gis/saga-gis.SlackBuild
+++ b/gis/saga-gis/saga-gis.SlackBuild
@@ -65,20 +65,19 @@ set -e
 
 # unixODBC is needed in 32 bit systems instead of libiodbc released
 # with Slackware 15.0. The slackbuild stops if unixODBC is not installed
-if [[ "$ARCH" = "i586" || "$ARCH" = "i686" ]] ; then
-  if ! [ -f /usr/lib/libodbc.so ] ; then
-    echo "";
-    echo "";
-    echo "";
-    echo "******************** WARNING *********************";
-    echo " This script cannot be executed in 32 bit systems ";
-    echo " with iODBC as default ODBC library installed.    ";
-    echo " The current process will be stopped.             ";
-    echo " Please install the unixODBC package from the     ";
-    echo " slackbuild available in the SBo repository.      ";
-    echo "**************************************************";
-    exit 1;
-  fi
+if [ -f /usr/lib/libiodbc.so ] ; then
+  echo ""
+  echo ""
+  echo ""
+  echo "******************** WARNING *********************"
+  echo " This script cannot be executed in 32 bit systems "
+  echo " with iODBC as default ODBC library installed.    "
+  echo " The current process will be stopped.             "
+  echo " Please uninstall libiodbc package and then       "
+  echo " unixODBC from the slackbuild available in the SBo"
+  echo " repository.                                      "
+  echo "**************************************************"
+  exit 1;
 fi
 
 # Look if the system has PDAL installed
